=== package-url/purl-spec/schemas/purl-type-definition.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://packageurl.org/schemas/purl-type-definition.schema-1.0.json",
  "title": "Package-URL Type Definition",
  "description": "Schema to specify a Package-URL (PURL) type as a structured definition.",
  "type": "object",
  "additionalProperties": false,
  "definitions": {
    "requirement": {
      "title": "Component requirement",
      "description": "States if this PURL component is required, optional, or prohibited.",
      "type": "string",
      "enum": [
        "required",
        "optional",
        "prohibited"
      ],
      "meta:enum": {
        "required": "This PURL component is required for this PURL type.",
        "optional": "This PURL component is optional for this PURL type.",
        "prohibited": "This PURL component is prohibited: it must not be present for this PURL type."
      }
    },
    "purl_component_definition": {
      "title": "PURL component definition",
      "description": "PURL component definition properties that apply to most PURL components",
      "type": "object",
      "properties": {
        "permitted_characters": {
          "title": "Permitted characters in this PURL component",
          "description": "Regular expression (ECMA-262 dialect) defining the 'Permitted characters' for this component of this Package-URL type. If provided, this must be a subset of the 'Permitted characters' defined in the PURL specification.",
          "type": "string",
          "format": "regex"
        },
        "case_sensitive": {
          "title": "Case sensitive",
          "description": "true if this PURL component is case sensitive. If false, the canonical form must be lowercased.",
          "type": "boolean",
          "default": true
        },
        "normalization_rules": {
          "title": "Normalization rules",
          "description": "List of rules to normalize this component for this PURL type. These are plain text, unstructured rules as some require programming and cannot be enforced only with a schema. Tools are expected to apply these rules programmatically.",
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "native_name": {
          "title": "Native name",
          "description": "The native name of this PURL component in the package ecosystem. For instance, the 'namespace' for the 'maven' type is 'groupId', and 'scope' for the 'npm' PURL type.",
          "type": "string"
        },
        "note": {
          "title": "Note",
          "description": "Extra note text.",
          "type": "string"
        }
      }
    }
  },
  "required": [
    "$id",
    "type",
    "type_name",
    "description",
    "repository",
    "namespace_definition",
    "name_definition",
    "examples"
  ],
  "properties": {
    "$schema": {
      "title": "JSON schema",
      "description": "Contains the URL of the JSON schema for Package-URL type definition.",
      "constant": "https://packageurl.org/schemas/purl-type.schema-1.0.json",
      "format": "uri"
    },
    "$id": {
      "title": "PURL type definition id",
      "description": "The unique identifier URI for this PURL type definition.",
      "type": "string",
      "pattern": "^https:\\/\\/packageurl\\.org/types/[a-z0-9-]+-definition\\.json$"
    },
    "type": {
      "title": "PURL type",
      "description": "The type string for this Package-URL type.",
      "type": "string",
      "pattern": "^[a-z][a-z0-9-\\.]+$",
      "examples": [
        "maven",
        "npm",
        "pypi"
      ]
    },
    "type_name": {
      "title": "Type name",
      "description": "The name for this PURL type.",
      "type": "string",
      "examples": [
        "Apache Maven",
        "Python Package"
      ]
    },
    "description": {
      "title": "Description",
      "description": "The description of this PURL type.",
      "type": "string"
    },
    "repository": {
      "title": "Repository",
      "description": "Package repository usage for this PURL type.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "use_repository"
      ],
      "properties": {
        "use_repository": {
          "title": "Use repository",
          "description": "true if this PURL type use a public package repository.",
          "type": "boolean",
          "default": false
        },
        "default_repository_url": {
          "title": "Default repository URL",
          "description": "The default public repository URL for this PURL type",
          "type": "string",
          "format": "uri"
        },
        "note": {
          "title": "Note",
          "description": "Extra note text.",
          "type": "string"
        }
      }
    },
    "namespace_definition": {
      "title": "Namespace definition",
      "description": "Definition of the namespace component for this PURL type.",
      "type": "object",
      "required": [
        "requirement"
      ],
      "properties": {
        "requirement": {
          "$ref": "#/definitions/requirement"
        }
      },
      "allOf": [
        {
          "$ref": "#/definitions/purl_component_definition"
        }
      ]
    },
    "name_definition": {
      "title": "Name definition",
      "description": "Definition of the name component for this PURL type.",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/purl_component_definition"
        }
      ]
    },
    "version_definition": {
      "title": "Version definition",
      "description": "Definition of the version component for this PURL type.",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/purl_component_definition"
        }
      ]
    },
    "qualifiers_definition": {
      "title": "Qualifiers definition",
      "description": "Definition for the qualifiers specific to this PURL type.",
      "type": "array",
      "additionalItems": false,
      "uniqueItems": true,
      "items": {
        "title": "Qualifiers definition",
        "description": "Definition of a qualifier specific to this PURL type.",
        "type": "object",
        "additionalProperties": false,
        "required": [
          "key",
          "description"
        ],
        "properties": {
          "key": {
            "title": "Qualifier key",
            "description": "The key for the qualifier.",
            "type": "string"
          },
          "requirement": {
            "$ref": "#/definitions/requirement"
          },
          "description": {
            "title": "Description",
            "description": "The description of this qualifier.",
            "type": "string"
          },
          "default_value": {
            "title": "Default value",
            "description": "The optional default value of this qualifier if not provided.",
            "type": "string"
          },
          "native_name": {
            "title": "Native name",
            "description": "The equivalent native name for this qualifier key.",
            "type": "string"
          }
        }
      }
    },
    "subpath_definition": {
      "title": "Subpath definition",
      "description": "Definition for the subpath for this PURL type.",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/purl_component_definition"
        }
      ]
    },
    "examples": {
      "title": "PURL examples",
      "description": "Example of valid, canonical PURLs for this package type.",
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "string",
        "pattern": "^pkg:[a-z][a-z0-9-\\.]+/.*$"
      }
    },
    "note": {
      "title": "Note",
      "description": "Note about this PURL type.",
      "type": "string"
    },
    "reference_urls": {
      "title": "Reference URLs",
      "description": "Optional list of informational reference URLs about this PURL type.",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "format": "uri"
      }
    }
  }
}

=== package-url/purl-spec/types/swift-definition.json
{
  "$schema": "https://packageurl.org/schemas/purl-type-definition.schema-1.0.json",
  "$id": "https://packageurl.org/types/swift-definition.json",
  "type": "swift",
  "type_name": "Swift packages",
  "description": "Swift packages",
  "repository": {
    "use_repository": true,
    "note": "There is no default package repository, this should be implied from namespace."
  },
  "namespace_definition": {
    "requirement": "required",
    "note": "The namespace is source host and user/organization and is required.",
    "case_sensitive": true
  },
  "name_definition": {
    "case_sensitive": true,
    "native_name": "repository name"
  },
  "version_definition": {
    "case_sensitive": true,
    "native_name": "package version"
  },
  "examples": [
    "pkg:swift/github.com/Alamofire/Alamofire@5.4.3",
    "pkg:swift/github.com/RxSwiftCommunity/RxFlow@2.12.4"
  ]
}

=== package-url/purl-spec/types/github-definition.json
{
  "$schema": "https://packageurl.org/schemas/purl-type-definition.schema-1.0.json",
  "$id": "https://packageurl.org/types/github-definition.json",
  "type": "github",
  "type_name": "GitHub",
  "description": "GitHub-based packages",
  "repository": {
    "use_repository": true,
    "default_repository_url": "https://github.com"
  },
  "namespace_definition": {
    "requirement": "required",
    "case_sensitive": false,
    "native_name": "user or organization",
    "note": "The namespace is the user or organization. It is not case sensitive and must be lowercased."
  },
  "name_definition": {
    "case_sensitive": false,
    "native_name": "repository name",
    "note": "The name is the repository name. It is not case sensitive and must be lowercased."
  },
  "version_definition": {
    "native_name": "commit or tag",
    "note": "The version is a commit or tag."
  },
  "examples": [
    "pkg:github/package-url/purl-spec@244fd47e07d1004",
    "pkg:github/package-url/purl-spec@244fd47e07d1004#everybody/loves/dogs"
  ]
}

=== package-url/purl-spec/types/deb-definition.json
{
  "$schema": "https://packageurl.org/schemas/purl-type-definition.schema-1.0.json",
  "$id": "https://packageurl.org/types/deb-definition.json",
  "type": "deb",
  "type_name": "Debian package",
  "description": "Debian packages, Debian derivatives, and Ubuntu packages",
  "repository": {
    "use_repository": true,
    "note": "There is no default package repository, this should be implied either from the distro qualifiers key or using a base url as a repository_url qualifiers key."
  },
  "namespace_definition": {
    "native_name": "vendor",
    "is_case_sensitve": false,
    "note": "The namespace is the \"vendor\" name such as \"debian\" or \"ubuntu\". It is not case sensitive and must be lowercased.",
    "requirement": "required"
  },
  "name_definition": {
    "native_name": "name",
    "is_case_sensitve": false,
    "note": "The name is not case sensitive and must be lowercased."
  },
  "version_definition": {
    "native_name": "version",
    "note": "The version is the version of the binary (or source) package."
  },
  "qualifiers_definition": [
    {
      "key": "arch",
      "description": "arch is the qualifiers key for a package architecture. The special value arch=source identifies a Debian source package that usually consists of a Debian Source control file (.dsc) and corresponding upstream and Debian sources. The dpkg-query command can print the name and version of the corresponding source package of a binary package, e.g. dpkg-query -f ${source:Package} ${source:Version} -W <binary package name>"
    }
  ],
  "examples": [
    "pkg:deb/debian/curl@7.50.3-1?arch=i386&distro=jessie",
    "pkg:deb/debian/dpkg@1.19.0.4?arch=amd64&distro=stretch",
    "pkg:deb/ubuntu/dpkg@1.19.0.4?arch=amd64",
    "pkg:deb/debian/attr@1:2.4.47-2?arch=source",
    "pkg:deb/debian/attr@1:2.4.47-2%2Bb1?arch=amd64"
  ]
}

=== package-url/purl-spec/types/pub-definition.json
{
  "$schema": "https://packageurl.org/schemas/purl-type-definition.schema-1.0.json",
  "$id": "https://packageurl.org/types/pub-definition.json",
  "type": "pub",
  "type_name": "Pub",
  "description": "Dart and Flutter pub packages",
  "repository": {
    "use_repository": true,
    "default_repository_url": "https://pub.dartlang.org"
  },
  "namespace_definition": {
    "requirement": "prohibited",
    "note": "there is no namespace"
  },
  "name_definition": {
    "native_name": "name",
    "case_sensitive": false,
    "permitted_characters": "^[a-z0-9_]",
    "normalization_rules": [
      "Replace non-[a-z] letters, non-[0-9] digits with underscore _"
    ],
    "note": "Pub normalizes all package names to be lowercase and using underscores. The only allowed characters are [a-z0-9_]. More information on pub naming and versioning is available in the pubspec documentation https://dart.dev/tools/pub/pubspec"
  },
  "version_definition": {
    "native_name": "version"
  },
  "examples": [
    "pkg:pub/characters@1.2.0",
    "pkg:pub/flutter@0.0.0"
  ]
}

=== package-url/purl-spec/types/cocoapods-definition.json
{
  "$schema": "https://packageurl.org/schemas/purl-type-definition.schema-1.0.json",
  "$id": "https://packageurl.org/types/cocoapods-definition.json",
  "type": "cocoapods",
  "type_name": "CocoaPods",
  "description": "CocoaPods pods",
  "repository": {
    "use_repository": true,
    "default_repository_url": "https://cdn.cocoapods.org/"
  },
  "namespace_definition": {
    "requirement": "prohibited",
    "note": "there is no namespace"
  },
  "name_definition": {
    "case_sensitive": true,
    "native_name": "pod name",
    "note": "The name is the pod name and is case sensitive, cannot contain whitespace, a plus (+) character, or begin with a period (.)."
  },
  "version_definition": {
    "native_name": "package version",
    "note": "The version is the package version."
  },
  "subpath_definition": {
    "note": "The purl subpath is used to represent a pods subspec (if present)."
  },
  "examples": [
    "pkg:cocoapods/AFNetworking@4.0.1",
    "pkg:cocoapods/MapsIndoors@3.24.0",
    "pkg:cocoapods/ShareKit@2.0#Twitter",
    "pkg:cocoapods/GoogleUtilities@7.5.2#NSData+zlib"
  ]
}

=== package-url/purl-spec/types/conda-definition.json
{
  "$schema": "https://packageurl.org/schemas/purl-type-definition.schema-1.0.json",
  "$id": "https://packageurl.org/types/conda-definition.json",
  "type": "conda",
  "type_name": "Conda",
  "description": "conda is for Conda packages",
  "repository": {
    "use_repository": true,
    "default_repository_url": "https://repo.anaconda.com"
  },
  "namespace_definition": {
    "note": "There is no namespace for Conda packages.",
    "requirement": "prohibited"
  },
  "name_definition": {
    "requirement": "required",
    "native_name": "name",
    "note": "The name is the package name."
  },
  "version_definition": {
    "requirement": "required",
    "native_name": "version",
    "note": "The version is the package version."
  },
  "qualifiers_definition": [
    {
      "key": "build",
      "requirement": "optional",
      "description": "the build string."
    },
    {
      "key": "channel",
      "requirement": "optional",
      "description": "the package stored location."
    },
    {
      "key": "subdir",
      "requirement": "optional",
      "description": "the associated platform."
    },
    {
      "key": "type",
      "requirement": "optional",
      "description": "package type."
    }
  ],
  "examples": [
    "pkg:conda/absl-py@0.4.1?build=py36h06a4308_0&channel=main&subdir=linux-64&type=tar.bz2",
    "pkg:conda/numpy@1.20.3?subdir=linux-64",
    "pkg:conda/python@3.9.7?build=h70747c6_1&channel=defaults&subdir=osx-64"
  ]
}

=== package-url/purl-spec/types/pear-definition.json
{
  "$schema": "https://packageurl.org/schemas/purl-type-definition.schema-1.0.json",
  "$id": "https://packageurl.org/types/pear-definition.json",
  "type": "pear",
  "type_name": "PEAR/PECL",
  "description": "PEAR and PECL PHP packages",
  "repository": {
    "use_repository": true,
    "note": "the depository URL is derived from the `namespace`"
  },
  "namespace_definition": {
    "requirement": "required",
    "case_sensitive": true,
    "normalization_rules": [ "The domain portion of the channel MUST be lowercased." ],
    "native_name": "channel",
    "note": "The `namespace` is the channel of the package."
  },
  "name_definition": {
    "native_name": "package",
    "case_sensitive": true
  },
  "version_definition": {
    "native_name": "version"
  },
  "examples": [
    "pkg:pear/pear.php.net/Text_Password@1.2.1",
    "pkg:pear/pecl.php.net/APCu@5.1.23"
  ]
}

=== package-url/purl-spec/types/hackage-definition.json
{
  "$schema": "https://packageurl.org/schemas/purl-type-definition.schema-1.0.json",
  "$id": "https://packageurl.org/types/hackage-definition.json",
  "type": "hackage",
  "type_name": "Haskell package",
  "description": "Haskell packages",
  "repository": {
    "use_repository": true,
    "default_repository_url": "https://hackage.haskell.org"
  },
  "namespace_definition": {
    "requirement": "prohibited",
    "note": "there is no namespace"
  },
  "name_definition": {
    "case_sensitive": true,
    "native_name": "name",
    "normalization_rules": [
      "Apply kebab-case"
    ],
    "note": "The name is case sensitive and use kebab-case."
  },
  "version_definition": {
    "native_name": "version",
    "note": "The version is package version."
  },
  "examples": [
    "pkg:hackage/a50@0.5",
    "pkg:hackage/AC-HalfInteger@1.2.1",
    "pkg:hackage/3d-graphics-examples@0.0.0.2"
  ]
}
